name: Minha API Rest Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2
      
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verificar código com flake8
      run: |
        flake8 api_rest tests
        
    - name: Executar testes com unittest e verificar cobertura de código
      run: |
        coverage run -m unittest discover
        coverage report
        
    - name: Fazer upload do relatório de cobertura
      uses: actions/upload-artifact@v2
      with:
        name: relatorio-cobertura
        path: ./htmlcov
