name: API Rest Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r Stars/requirements.txt

    - name: Verificar código com flake8
      run: flake8 Stars/api_rest --ignore=E501,E402

    - name: Executar testes com unittest e gerar cobertura de código
      run: |
        pip install coverage
        coverage run -m unittest discover Stars/api_rest/tests
        coverage html

    - name: Fazer upload do relatório de cobertura
      uses: actions/upload-artifact@v3
      with:
        name: relatorio-cobertura
        path: htmlcov
