name: Minha API Rest Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api_rest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Atualizando o pip
      run: python -m pip install --upgrade pip

    - name: Instalar dependências
      run: pip install -r Stars/requirements.txt

    - name: Verificar código com flake8 (--ignore=E501)
      run: flake8 Stars/api_rest --ignore=E501

    - name: Executar testes com unittest e cobertura de código
      run: coverage run -m unittest discover Stars/api_rest/tests --report

    - name: Fazer upload do relatório de cobertura
      uses: actions/upload-artifact@v2
      with:
        name: relatorio-cobertura
        path: ./htmlcov
